name: PlayManagerCM
version: 2.2
main: com.nerix.playmanagercm.PlayManagerCM
api-version: "1.20"
authors: [_Nerix]
commands:
  compass:
    description: Команда для компаса
    usage: /compass <player|marker|addmarker|delmarker> [arguments]
    aliases: [compas, cm]
  ping:
    description: Ваш и пинг игрока
    usage: /ping [player]
  msg:
    description: Личные сообщения
    usage: /msg <player> <message>
    aliases: [m, tell, whisper, w]
  rank:
    description: Выдача, отмена ранга игрока
    usage: /rank <set|remove|reload> [player] [rank]
    permission: playmanager.admin
  playmanagercm:
    description: Перезагрузка плагина
    usage: /playmanagercm <reload>
    aliases: [pmcm]
    permission: playmanager.admin
